version: "3"
services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surveyor_development
    container_name: surveyor-postgres
    networks:
      - surveyor
  surveyor:
    image: aisrael/surveyor
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@surveyor-postgres/surveyor_development
    networks:
      - surveyor
networks:
  surveyor:
