---
openapi: 3.0.1
info:
  title: Surveyor API
  version: v1
paths:
  "/api/v1/averages":
    get:
      summary: averages
      produces:
      - application/json
      responses:
        '200':
          description: successful
          schema:
            type: object
            properties:
              questionAverages:
                type: array
                items:
                  type: object
                  properties:
                    questionId:
                      type: integer
                      example: 1
                    averageScore:
                      type: number
                      example: 4.0
                  required:
                  - questionId
                  - averageScore
  "/api/v1/scored-question-distributions":
    get:
      summary: scored-question-distributions
      produces:
      - application/json
      responses:
        '200':
          description: successful
          schema:
            type: object
            properties:
              scored_question_distributions:
                type: array
                items:
                  type: object
                  properties:
                    questionId:
                      type: integer
                      example: 1
                    responseFrequencies:
                      type: array
                      items:
                        type: object
                        properties:
                          score:
                            type: integer
                          frequency:
                            type: integer
  "/api/v1/profile-segment-scores-by-gender":
    get:
      summary: profile-segment-scores-by-gender
      produces:
      - application/json
      responses:
        '200':
          description: successful
          schema:
            type: object
            properties:
              profileSegmentScores:
                type: array
                items:
                  type: object
                  properties:
                    segment:
                      type: object
                      properties:
                        gender:
                          type: string
                    questionAverages:
                      type: array
                      items:
                        type: object
                        properties:
                          questionId:
                            type: integer
                          averageScore:
                            type: number
  "/api/v1/responses":
    post:
      summary: submit responses
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: payload
        in: body
        schema:
          type: object
          properties:
            respondentIdentifier:
              type: string
              example: '00001'
            responses:
              type: array
              items:
                type: object
                properties:
                  questionId:
                    type: integer
                    example: 1
                  respondentId:
                    type: string
                    example: '00001'
                  body:
                    oneOf:
                    - type: integer
                      example: 4
                    - type: string
                      example: Unclear expectations
      responses:
        '200':
          description: successful
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    respondentIdentifier:
                      type: string
                      example: '00001'
                    questionId:
                      type: integer
                      example: 1
                    body:
                      oneOf:
                      - type: integer
                        example: 4
                      - type: string
                        example: Unclear expectations
                  required:
                  - id
                  - respondentIdentifier
                  - questionId
                  - body
            required:
            - data
    get:
      summary: list responses
      responses:
        '200':
          description: successful
          schema:
            type: object
            properties:
              responses:
                type: array
                items:
                  type: object
                  properties:
                    questionId:
                      type: integer
                      example: 1
                    body:
                      type: string
                      example: '4'
                  required:
                  - questionId
                  - body
